version: "3.8"
services:
    # Symfony apache project container
    www:
        build: docker/php
        container_name: tutorial_symfony
        ports:
          - "8741:80"
        volumes:
            - ./vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - tutorial

networks:
    tutorial: